name: Build Validation

# Simple workflow to ensure PR builds don't fail
on:
  pull_request:
    branches: [develop, deployment]

jobs:
  validate-builds:
    name: Validate Frontend & Backend Builds
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      # Frontend Build
      - name: Install frontend dependencies
        run: npm ci --prefix frontend
        
      - name: Build frontend
        run: npm run build --prefix frontend
        
      # Backend Build  
      - name: Install backend dependencies
        run: npm ci --prefix backend
        
      - name: Build backend
        run: npm run build --prefix backend
        
      # Final verification
      - name: Verify builds completed
        run: |
          echo "Checking build outputs..."
          if [ ! -d "frontend/dist" ]; then
            echo "❌ Frontend build failed"
            exit 1
          fi
          if [ ! -d "backend/dist" ]; then
            echo "❌ Backend build failed" 
            exit 1
          fi
          echo "✅ Both builds completed successfully!"
