name: Comprehensive PR Checks

on:
  pull_request:
    branches: [develop, deployment]

env:
  NODE_VERSION: '18'

jobs:
  frontend-checks:
    name: Frontend Build & Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
          
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Check formatting
        working-directory: ./frontend
        run: npm run format:check
        
      - name: Run linting
        working-directory: ./frontend
        run: npm run lint
        
      - name: TypeScript compilation check
        working-directory: ./frontend
        run: npx tsc --noEmit
        
      - name: Build application
        working-directory: ./frontend
        run: npm run build
        
      - name: Verify build output
        working-directory: ./frontend
        run: |
          if [ ! -d "dist" ]; then
            echo "❌ Build failed - dist directory not found"
            exit 1
          fi
          echo "✅ Frontend build successful"
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: frontend/dist/
          retention-days: 1

  backend-checks:
    name: Backend Build & Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'
          
      - name: Install dependencies
        working-directory: ./backend
        run: npm ci
        
      - name: Check formatting (optional)
        working-directory: ./backend
        run: npm run format
        continue-on-error: true
        
      - name: Run linting
        working-directory: ./backend
        run: npm run lint
        
      - name: Run tests (optional)
        working-directory: ./backend
        run: npm run test
        continue-on-error: true
        
      - name: Build application
        working-directory: ./backend
        run: npm run build
        
      - name: Verify build output
        working-directory: ./backend
        run: |
          if [ ! -d "dist" ]; then
            echo "❌ Build failed - dist directory not found"
            exit 1
          fi
          echo "✅ Backend build successful"
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backend-dist
          path: backend/dist/
          retention-days: 1

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Audit frontend dependencies
        working-directory: ./frontend
        run: |
          npm ci
          npm audit --audit-level=moderate
        continue-on-error: true
        
      - name: Audit backend dependencies
        working-directory: ./backend
        run: |
          npm ci
          npm audit --audit-level=moderate
        continue-on-error: true
