name: Deploy Backend to Azure

on:
  push:
    branches: [deployment]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: "backend/package-lock.json"

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Build
        run: |
          cd backend
          npm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Prepare optimized deployment package
        run: |
          # Create minimal deployment package structure
          mkdir -p deploy

          # Copy only essential production files
          cp -r backend/dist deploy/
          cp backend/package.json deploy/
          cp backend/package-lock.json deploy/

          # Create production-only node_modules
          cd deploy
          npm ci --production --no-optional

          # Add Azure configuration
          echo 'node ./dist/src/main.js' > ./startup.sh
          chmod +x ./startup.sh

          # Remove unnecessary files to save space
          find . -name "*.map" -type f -delete
          find . -name "*.spec.*" -type f -delete
          find . -name "*.test.*" -type f -delete

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "booking-app-backend"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "./backend"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          ALLOWED_ORIGINS: "https://agreeable-grass-049dc8010.6.azurestaticapps.net,http://localhost:5180"
          NODE_ENV: "production"

      - name: Post-deployment verification
        if: success()
        run: |
          echo "Deployment completed, waiting for app to start..."
          sleep 15
          curl -s "https://booking-app-backend-duh9encbeme0awca.northeurope-01.azurewebsites.net/health" || echo "App may still be starting"
