# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - booking-app-backend

on:
  push:
    branches:
      - SCRUM-133-deploy-the-app
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: "backend/package-lock.json"

      # Use production flag for leaner builds
      - name: npm install and build
        run: |
          cd backend
          npm ci --production
          npm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      # Create slim deployment package by excluding unnecessary files
      - name: Create slim deployment package
        run: |
          cd backend
          # Remove development files not needed in production
          rm -rf tests/ test/ .eslintrc* tsconfig.json
          # Create an optimized zip file with parallel compression
          apt-get update && apt-get install -y pigz
          tar cf - . | pigz -9 > ../release.tgz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.tgz
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unpack artifact efficiently
        run: mkdir -p app && tar -xzf release.tgz -C app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9F8DBAB572D14E1685EE75B41915FCD2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BAD9EECA19F943F18A65D60C0C3448AF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7BC8E4BEADA04C2EA793E85FD9389394 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "booking-app-backend"
          slot-name: "Production"
          package: app/
          startup-command: "NODE_OPTIONS='--max-old-space-size=4096' SUPABASE_URL=${{ secrets.SUPABASE_URL }} SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} ALLOWED_ORIGINS=https://agreeable-grass-049dc8010.4.azurestaticapps.net,https://agreeable-grass-049dc8010.6.azurestaticapps.net,http://localhost:5180 npm run start:prod"
